export interface GrowthQuestion {
  id: number;
  category: string;
  emoji: string;
  goodAction: string;
  badAction: string;
  goodResult: string;
  badResult: string;
}

export const GROWTH_QUESTIONS: GrowthQuestion[] = [
  // ── Money & Buying ────────────────────────────────────────────────────────
  {
    id: 1, category: 'Money & Buying', emoji: '💰',
    goodAction: 'Practice math every day so you understand prices and money',
    badAction: 'Skip math — "I\'ll never use it in real life!"',
    goodResult: 'You can always afford the toys, games, and gadgets you love 🎮',
    badResult: 'You never have enough money for the things you really want 😢',
  },
  {
    id: 2, category: 'Money & Buying', emoji: '💰',
    goodAction: 'Learn your times tables really well',
    badAction: 'Give up on multiplication because it feels too hard',
    goodResult: 'Win card games, understand discounts, and never get cheated at a shop',
    badResult: 'Get confused with prices and lose money without even realizing it',
  },
  {
    id: 3, category: 'Money & Buying', emoji: '💰',
    goodAction: 'Work hard in school and keep building real skills',
    badAction: 'Stop caring about school — "playing is more fun right now"',
    goodResult: 'Earn enough to buy any toy, Lego set, or robot kit you dream about 🤖',
    badResult: 'Watch your friends buy cool things while you struggle to afford anything',
  },
  {
    id: 4, category: 'Money & Buying', emoji: '💰',
    goodAction: 'Learn how computers and coding work',
    badAction: 'Say "I don\'t need to know how computers actually work"',
    goodResult: 'Build your own games, apps, or robots — and earn real money doing it! 💻',
    badResult: 'Miss out on the most exciting and best-paying jobs of the future',
  },
  {
    id: 5, category: 'Money & Buying', emoji: '💰',
    goodAction: 'Study and practice English every single week',
    badAction: 'Refuse to practice English — "I already know enough"',
    goodResult: 'Play online games and make friends with kids from all over the world 🌍',
    badResult: 'Never understand your favorite games, shows, or instructions in English',
  },
  {
    id: 6, category: 'Money & Buying', emoji: '💰',
    goodAction: 'Save a little bit of your pocket money every week',
    badAction: 'Spend every coin the moment you get it',
    goodResult: 'Save enough to buy that big Lego set or gaming console ALL by yourself 🎉',
    badResult: 'Always broke exactly when something amazing comes out',
  },
  {
    id: 7, category: 'Money & Buying', emoji: '💰',
    goodAction: 'Read books about how businesses work',
    badAction: 'Ignore all money lessons — "that\'s boring adult stuff"',
    goodResult: 'Start your own business selling crafts, games, or things you make 🏪',
    badResult: 'Always need others for money and never feel free or independent',
  },
  {
    id: 8, category: 'Money & Buying', emoji: '💰',
    goodAction: 'Practice solving hard problems without giving up',
    badAction: 'Give up the moment something feels difficult',
    goodResult: 'Build amazing things like robots, apps, or inventions that sell 💡',
    badResult: 'Always need someone else to fix your problems — no independence',
  },
  {
    id: 9, category: 'Money & Buying', emoji: '💰',
    goodAction: 'Graduate from school and keep learning new skills every year',
    badAction: 'Drop out because studying feels boring right now',
    goodResult: 'Get your dream job that pays enough for everything you love in life',
    badResult: 'Work exhausting jobs that barely cover food — nothing left for fun',
  },
  {
    id: 10, category: 'Money & Buying', emoji: '💰',
    goodAction: 'Keep learning something new every day, even after school',
    badAction: 'Spend every free moment playing with zero learning at all',
    goodResult: 'Be the smart friend everyone wants on their team for quizzes and games',
    badResult: 'Feel left behind when friends talk about things you never learned',
  },

  // ── Health & Energy ───────────────────────────────────────────────────────
  {
    id: 11, category: 'Health & Energy', emoji: '💪',
    goodAction: 'Sleep at the right time every night — even before a big game day',
    badAction: 'Stay up super late playing video games or watching videos every night',
    goodResult: 'Wake up sharp, focused, and ready to beat any challenge 🌟',
    badResult: 'Fall asleep in class and miss everything — then fail the test 😴',
  },
  {
    id: 12, category: 'Health & Energy', emoji: '💪',
    goodAction: 'Move and exercise — join a sport, dance, or just play outside',
    badAction: 'Sit still all day — never move unless you have to',
    goodResult: 'Feel strong, fast, and full of energy every single day ⚡',
    badResult: 'Feel slow and tired all the time — even walking up stairs feels hard',
  },
  {
    id: 13, category: 'Health & Energy', emoji: '💪',
    goodAction: 'Eat real food — fruits, vegetables, rice, meat',
    badAction: 'Only eat candy, chips, and sugary drinks every day',
    goodResult: 'Have strong bones, sharp brain, and energy to play ALL day 🏃',
    badResult: 'Get cavities, feel foggy, and get sick more often than your friends',
  },
  {
    id: 14, category: 'Health & Energy', emoji: '💪',
    goodAction: 'Take a deep breath and calm down when you\'re angry or frustrated',
    badAction: 'Throw a fit or scream every time something doesn\'t go your way',
    goodResult: 'Stay in control and find better solutions — friends love playing with you',
    badResult: 'Push away your friends and get in trouble — over and over again',
  },
  {
    id: 15, category: 'Health & Energy', emoji: '💪',
    goodAction: 'Drink water throughout the day — even during gaming sessions',
    badAction: 'Only drink soda and energy drinks and forget water completely',
    goodResult: 'Your brain works faster, you focus longer, and you feel amazing',
    badResult: 'Headaches, bad concentration, and crash after just one hour of activity',
  },
  {
    id: 16, category: 'Health & Energy', emoji: '💪',
    goodAction: 'Learn first aid basics at school — how to help someone who\'s hurt',
    badAction: 'Think first aid class is a waste of time and ignore it',
    goodResult: 'One day you could actually save a friend\'s or family member\'s life 🦸',
    badResult: 'Panic completely when someone gets hurt — no idea what to do',
  },
  {
    id: 17, category: 'Health & Energy', emoji: '💪',
    goodAction: 'Wash hands, brush teeth, and keep yourself clean every day',
    badAction: 'Skip brushing and washing — "it\'s not that important"',
    goodResult: 'Stay healthy and keep all your beautiful teeth for life 😁',
    badResult: 'Catch colds more often and end up with painful cavities at the dentist',
  },
  {
    id: 18, category: 'Health & Energy', emoji: '💪',
    goodAction: 'Talk to someone you trust when you feel sad or worried',
    badAction: 'Keep all your bad feelings locked inside and never tell anyone',
    goodResult: 'Feel lighter, think clearer, and have friends who actually understand you',
    badResult: 'Feel alone and heavy with worries that just keep piling up',
  },
  {
    id: 19, category: 'Health & Energy', emoji: '💪',
    goodAction: 'Take breaks while studying or playing — rest your eyes and stretch',
    badAction: 'Stare at a screen for 6+ hours without any break at all',
    goodResult: 'Stay sharp and avoid eye strain — enjoy screens for many more years',
    badResult: 'Hurt your eyes, get headaches, and need glasses much sooner',
  },
  {
    id: 20, category: 'Health & Energy', emoji: '💪',
    goodAction: 'Learn about why your body needs different foods from science class',
    badAction: 'Ignore health and science — "It\'s boring and I don\'t care"',
    goodResult: 'Make smart food choices that keep you energetic, strong, and healthy',
    badResult: 'Follow bad trends that hurt your body without you even knowing it',
  },

  // ── Friendships & Respect ─────────────────────────────────────────────────
  {
    id: 21, category: 'Friendships & Respect', emoji: '🤝',
    goodAction: 'Explain a hard concept to a classmate who doesn\'t understand',
    badAction: 'Never help others — "it\'s their problem, not mine"',
    goodResult: 'Become the friend everyone wants in their group — you\'re valued! 🌟',
    badResult: 'When YOU need help one day, nobody shows up for you',
  },
  {
    id: 22, category: 'Friendships & Respect', emoji: '🤝',
    goodAction: 'Do your own homework and projects with full effort',
    badAction: 'Copy classmates\' work every time — "easier and faster"',
    goodResult: 'Earn real trust and respect that lasts forever — from teachers and friends',
    badResult: 'Get caught cheating and lose everyone\'s trust — that follows you for years',
  },
  {
    id: 23, category: 'Friendships & Respect', emoji: '🤝',
    goodAction: 'Be brave and raise your hand even when you\'re not 100% sure',
    badAction: 'Stay completely silent — "I\'m scared of being wrong"',
    goodResult: 'Learn faster, get noticed, and become more confident every week',
    badResult: 'Stay confused and slowly fall far behind everyone around you',
  },
  {
    id: 24, category: 'Friendships & Respect', emoji: '🤝',
    goodAction: 'Admit it honestly when you make a mistake',
    badAction: 'Always blame someone else or make up excuses',
    goodResult: 'People trust you completely — that trust opens every single door',
    badResult: 'Lose friends one by one — nobody likes someone who never owns their mistakes',
  },
  {
    id: 25, category: 'Friendships & Respect', emoji: '🤝',
    goodAction: 'Share your Pokemon cards, Lego sets, or games with friends',
    badAction: 'Never share anything — "mine is mine, don\'t touch it"',
    goodResult: 'Always have friends to play with and people who share back with you 😊',
    badResult: 'End up playing alone because nobody wants to be around someone selfish',
  },
  {
    id: 26, category: 'Friendships & Respect', emoji: '🤝',
    goodAction: 'Study hard to make your parents proud of you',
    badAction: 'Give up on hard subjects without even really trying',
    goodResult: 'See pure joy and pride on your family\'s faces — that feeling is priceless 💛',
    badResult: 'Feel the sadness of disappointing the people who love you most',
  },
  {
    id: 27, category: 'Friendships & Respect', emoji: '🤝',
    goodAction: 'Listen carefully when someone else is talking — even if you disagree',
    badAction: 'Interrupt, argue, and talk over everyone who says something different',
    goodResult: 'People love talking with you — you always find solutions together',
    badResult: 'Nobody wants to discuss anything with you — you push people away',
  },
  {
    id: 28, category: 'Friendships & Respect', emoji: '🤝',
    goodAction: 'Include the kid who is sitting alone at lunch or recess',
    badAction: 'Ignore or make fun of anyone who seems different or left out',
    goodResult: 'Be known as a kind leader — someone truly worth looking up to 🦸',
    badResult: 'Be feared, not loved — and feel emptiness inside even with many "followers"',
  },
  {
    id: 29, category: 'Friendships & Respect', emoji: '🤝',
    goodAction: 'Keep your promises — if you say you\'ll do something, DO it',
    badAction: 'Make promises easily and break them just as easily',
    goodResult: 'Everyone knows your word means something — you become truly reliable',
    badResult: 'Friends stop counting on you — your word becomes worthless to others',
  },
  {
    id: 30, category: 'Friendships & Respect', emoji: '🤝',
    goodAction: 'Encourage a friend who is struggling and wants to give up',
    badAction: 'Laugh at friends when they fail or make mistakes',
    goodResult: 'Build lifelong friendships with people who will always support YOU too',
    badResult: 'Friends disappear when you need them — you taught them not to trust you',
  },

  // ── Skills & Creativity ───────────────────────────────────────────────────
  {
    id: 31, category: 'Skills & Creativity', emoji: '🎨',
    goodAction: 'Learn how to code — even just simple games or animations',
    badAction: 'Say "coding is only for super-genius people — not for me"',
    goodResult: 'Build your OWN video game and let your friends play it 🎮',
    badResult: 'Always play other people\'s games — never create your own',
  },
  {
    id: 32, category: 'Skills & Creativity', emoji: '🎨',
    goodAction: 'Join robotics club or learn how robots are built',
    badAction: 'Think robotics is "too nerdy" and walk away',
    goodResult: 'Build an actual working robot — and maybe win competitions! 🤖',
    badResult: 'Watch others win robotics trophies while wishing you had tried',
  },
  {
    id: 33, category: 'Skills & Creativity', emoji: '🎨',
    goodAction: 'Practice drawing, painting, or designing your own characters',
    badAction: 'Say "I can\'t draw — I\'m just not talented"',
    goodResult: 'Design characters for your own comic book, game, or cartoon one day 🎨',
    badResult: 'Never know what creative superpower was hiding inside you all along',
  },
  {
    id: 34, category: 'Skills & Creativity', emoji: '🎨',
    goodAction: 'Build things with Lego, blocks, or craft materials and experiment',
    badAction: 'Only consume — watch videos and play games but never BUILD anything',
    goodResult: 'Train your brain to think like an engineer — design real things one day',
    badResult: 'Great at watching others create, but never experience the joy of making',
  },
  {
    id: 35, category: 'Skills & Creativity', emoji: '🎨',
    goodAction: 'Read books about science, space, dinosaurs, or things you love',
    badAction: 'Refuse to read anything extra — "school books are already enough"',
    goodResult: 'Know amazing facts that make every conversation interesting 🦕🚀',
    badResult: 'Run out of interesting things to say — and miss so many cool ideas',
  },
  {
    id: 36, category: 'Skills & Creativity', emoji: '🎨',
    goodAction: 'Learn to play an instrument — piano, guitar, drums, or anything',
    badAction: 'Say "music lessons are boring — I\'ll skip those"',
    goodResult: 'Play songs that make people smile — music is a superpower for life 🎵',
    badResult: 'Miss one of the most joyful and brain-boosting skills you could ever have',
  },
  {
    id: 37, category: 'Skills & Creativity', emoji: '🎨',
    goodAction: 'Practice explaining your ideas clearly to others',
    badAction: 'Avoid talking in front of people — "I\'ll just stay quiet"',
    goodResult: 'Present your projects confidently and impress everyone in the room',
    badResult: 'Lose opportunities because you couldn\'t explain your great ideas clearly',
  },
  {
    id: 38, category: 'Skills & Creativity', emoji: '🎨',
    goodAction: 'Study science and understand how the things around you actually work',
    badAction: 'Memorize for tests only — never actually wonder WHY things work',
    goodResult: 'Fix things, invent things, understand the world deeply 🔬',
    badResult: 'Feel confused and helpless whenever technology or systems break down',
  },
  {
    id: 39, category: 'Skills & Creativity', emoji: '🎨',
    goodAction: 'Try new hobbies — cooking, origami, chess, photography, anything',
    badAction: 'Only do the same 2 or 3 things forever — "new things are scary"',
    goodResult: 'Discover a hidden passion that could shape your whole future career',
    badResult: 'Never find the thing that makes you feel truly alive and excited',
  },
  {
    id: 40, category: 'Skills & Creativity', emoji: '🎨',
    goodAction: 'Learn from your teachers, parents, and mentors — ask them questions',
    badAction: 'Think "I already know enough — I don\'t need anyone\'s advice"',
    goodResult: 'Skip years of painful mistakes by using others\' hard-earned wisdom',
    badResult: 'Learn everything the slow, painful, expensive way — all by yourself',
  },

  // ── Your Amazing Future ───────────────────────────────────────────────────
  {
    id: 41, category: 'Your Amazing Future', emoji: '🚀',
    goodAction: 'Wake up on time and start each day with a goal — even a small one',
    badAction: 'Wait until you "feel motivated" before doing anything useful',
    goodResult: 'Build the habit of winners — small steps add up to BIG achievements 🏆',
    badResult: 'Spend years waiting for motivation that never actually arrives',
  },
  {
    id: 42, category: 'Your Amazing Future', emoji: '🚀',
    goodAction: 'Set a fun goal — like mastering a Rubik\'s cube or finishing a hard game level',
    badAction: 'Give up on goals the moment they stop being easy',
    goodResult: 'Achieve harder and harder things — your confidence grows every time',
    badResult: 'Never finish what you start — and feel bad about yourself for it',
  },
  {
    id: 43, category: 'Your Amazing Future', emoji: '🚀',
    goodAction: 'Try your hardest in every subject — even the ones you don\'t love',
    badAction: 'Only try in subjects you already like — skip the rest',
    goodResult: 'Surprise yourself by discovering you\'re actually great at something new!',
    badResult: 'Miss your hidden talents because you never gave them a real chance',
  },
  {
    id: 44, category: 'Your Amazing Future', emoji: '🚀',
    goodAction: 'When you lose a game or fail a test — figure out WHY and try again',
    badAction: 'Rage quit when you lose — "this game is stupid anyway"',
    goodResult: 'Get better and better until you master things others thought were impossible',
    badResult: 'Stay at the same skill level forever — and miss the thrill of real improvement',
  },
  {
    id: 45, category: 'Your Amazing Future', emoji: '🚀',
    goodAction: 'After finishing a project or game, think: "What did I learn from this?"',
    badAction: 'Rush from one thing to the next without ever reflecting or thinking deeply',
    goodResult: 'Grow twice as fast as others — you actually USE what you experience',
    badResult: 'Keep making the same mistakes over and over without ever improving',
  },
  {
    id: 46, category: 'Your Amazing Future', emoji: '🚀',
    goodAction: 'Keep going when a skill is hard — like hard card combos or complex code',
    badAction: 'Quit immediately: "If it\'s hard, it\'s just not for me"',
    goodResult: 'Master rare skills almost nobody has — you become one-of-a-kind',
    badResult: 'Stay at beginner level in everything — never truly mastering anything',
  },
  {
    id: 47, category: 'Your Amazing Future', emoji: '🚀',
    goodAction: 'Dream about what you want to BUILD or CREATE one day and go for it',
    badAction: 'Dream small because you\'re scared people will laugh if you fail',
    goodResult: 'Live a life that amazes even YOU — bigger than you ever imagined',
    badResult: 'Wonder "what if I had actually tried...?" for the rest of your life',
  },
  {
    id: 48, category: 'Your Amazing Future', emoji: '🚀',
    goodAction: 'Focus on being better than YOU were yesterday',
    badAction: 'Compare yourself to others and feel jealous of what they have',
    goodResult: 'Become the very best version of YOU — unique and genuinely happy',
    badResult: 'Make others feel bad AND still not actually improve yourself at all',
  },
  {
    id: 49, category: 'Your Amazing Future', emoji: '🚀',
    goodAction: 'Study because you\'re curious and love understanding how things work',
    badAction: 'Cram everything just before the test — then forget it all after',
    goodResult: 'Build real knowledge that stays with you for life — it compounds! 🧠',
    badResult: 'Forget everything one week after the exam — all that effort wasted',
  },
  {
    id: 50, category: 'Your Amazing Future', emoji: '🚀',
    goodAction: 'Believe in yourself — "I can learn anything if I keep trying"',
    badAction: 'Tell yourself "I\'m just not smart enough" and stop trying',
    goodResult: 'Achieve things that make your whole family proud for generations 🌟',
    badResult: 'Leave your amazing potential locked inside you forever — untouched',
  },
];

export const CATEGORIES = [...new Set(GROWTH_QUESTIONS.map(q => q.category))];
